- name: Setup Frontend Node
  hosts: frontend
  become: true
  gather_facts: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
      when: ansible_distribution == "Ubuntu"
      notify: Restart NGINX
    - name: Install tools
      apt:
        name: "{{ item }}"
        state: present
      loop: [vim, curl, git]
    - name: Deploy HTML
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Deployed via Ansible</h1>"
      notify: Restart NGINX
  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
